### PR TITLE
Fixed q1, q3 and avg values on time line query reports

### LINKED ISSUE #175: Quartiles are not working on graphs that start from non-zero values

### PR DESCRIPTION
**Pull request by anttileppa**
Resolves #175

### CODE REVIEW

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisMultiselectQueryReportPage.java [hunk 1]
```diff
@@ -77,6 +77,6 @@ public Chart constructChart(ChartContext chartContext, QueryPage queryPage) {
       values.add(new Double(listOptionAnswerCounts.get(optionId)));
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisMultiselectQueryReportPage.java:77]: MAJOR Remove this "Double" constructor [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2129)

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisTimelineQueryReportPage.java [hunk 2]
```diff
@@ -92,12 +92,23 @@ public Chart constructChart(ChartContext chartContext, QueryPage queryPage) {
         if (xValues.get(i) == null || yValues.get(i) == null) {
           continue;
         }
+        
         int x = (int) ((xValues.get(i) - min) / step);
         int y = (int) ((yValues.get(i) - min) / step);
         values[x][y] = new Double(values[x][y] != null ? values[x][y] + 1 : 1);
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisTimelineQueryReportPage.java:98]: MAJOR Remove this "Double" constructor [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2129)

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java [hunk 3]
```diff
@@ -63,10 +63,9 @@
 
 public class ChartModelProvider {
 
-  public static Chart createBarChart(String chartCaption, String xLabel, List<String> categoryCaptions, List<Double> values, Double average, Double q1, Double q3) {
+  public static Chart createBarChart(String chartCaption, String xLabel, List<String> categoryCaptions, List<Double> values, Double min, Double max, Double average, Double q1, Double q3) {
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java]: MAJOR Method has 9 parameters, which is greater than 7 authorized. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00107)

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java [hunk 4]
```diff
@@ -123,15 +122,16 @@ public static Chart createBarChart(String chartCaption, String xLabel, List<Stri
...
+    addMarkerLine("A", translateMarkerToRange(size, min, max, average), 0.5d, xAxisPrimary);
+    addMarkerLine("Q1", translateMarkerToRange(size, min, max, q1), 0.5d, xAxisPrimary);
+    addMarkerLine("Q3", translateMarkerToRange(size, min, max, q3), 0.5d, xAxisPrimary);
 
     return cwaBar;
   }
 
-  public static Chart createBarChartHorizontal(String chartCaption, String xLabel, List<String> categoryCaptions, List<Double> values, Double average, Double q1, Double q3) {
-    ChartWithAxes chart = (ChartWithAxes) createBarChart(chartCaption, xLabel, categoryCaptions, values, average, q1, q3);
+  public static Chart createBarChartHorizontal(String chartCaption, String xLabel, List<String> categoryCaptions, List<Double> values, Double min, Double max, Double average, Double q1, Double q3) {
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java]: MAJOR Method has 9 parameters, which is greater than 7 authorized. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00107)

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java [hunk 5]
```diff
@@ -614,7 +614,7 @@ public static Chart createBubbleChart(String chartCaption, String xLabel, List<S
    * @return created chart
    */
   @SuppressWarnings ({"squid:S00107", "squid:S3776"})
-  public static Chart createBubbleChart(String chartCaption, String xLabel, List<String> xTickLabels, String yLabel, List<String> yTickLabels, int xAxisLabelRotation, int yAxisLabelRotation, Double[][] values, Double avgX, Double qX1, Double qX3, Double avgY, Double qY1, Double qY3) {
+  public static Chart createBubbleChart(String chartCaption, String xLabel, List<String> xTickLabels, String yLabel, List<String> yTickLabels, int xAxisLabelRotation, int yAxisLabelRotation, Double[][] values, Double minX, Double maxX, Double minY, Double maxY, Double avgX, Double qX1, Double qX3, Double avgY, Double qY1, Double qY3) {
     // TODO: Tick labels
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java:624]: INFO Complete the task associated to this TODO comment. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1135)

File: edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java [hunk 6]
```diff
@@ -614,7 +614,7 @@ public static Chart createBubbleChart(String chartCaption, String xLabel, List<S
...
     // TODO: y serie colors
```
Comment (sonarq) [inline edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java:625]: INFO Complete the task associated to this TODO comment. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1135)

**Comment by sonarq** [comment]
SonarQube analysis reported 86 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 14 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [FormQueryReportPage.java#L52](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/FormQueryReportPage.java#L52): Refactor this method to reduce its Cognitive Complexity from 20 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [FormQueryReportPage.java#L115](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/FormQueryReportPage.java#L115): Refactor this method to reduce its Cognitive Complexity from 20 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [ThesisTimelineQueryReportPage.java#L45](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisTimelineQueryReportPage.java#L45): Define a constant instead of duplicating this literal "timeline.value1" 3 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ThesisTimelineQueryReportPage.java#L70](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisTimelineQueryReportPage.java#L70): Refactor this method to reduce its Cognitive Complexity from 37 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [ChartModelProvider.java#L433](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java#L433): Refactor this method to reduce its Cognitive Complexity from 16 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [ChartModelProvider.java#L437](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/util/ChartModelProvider.java#L437): Change this "try" to a try-with-resources. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2093)
1. ![MAJOR][MAJOR] [FormQueryReportPage.java#L102](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/FormQueryReportPage.java#L102): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [FormQueryReportPage.java#L162](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/FormQueryReportPage.java#L162): Make this anonymous inner class a lambda [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1604)
1. ![MAJOR][MAJOR] [FormQueryReportPage.java#L195](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/FormQueryReportPage.java#L195): Remove this "Double" constructor [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2129)
1. ![MAJOR][MAJOR] [ThesisMultiselectQueryReportPage.java#L49](https://github.com/Metatavu/edelphi/blob/bb3b823f77a88c66e23a05a35b9b8564e5b1d5b8/edelphi/src/main/java/fi/metatavu/edelphi/pages/panel/admin/report/thesis/ThesisMultiselectQueryReportPage.java#L49): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
