### PR TITLE
Added sql script for fixing invalid query template setting encodings

### LINKED ISSUE #65: Query page settings encoding
Query page settings contain some xml encoded strings

### PR DESCRIPTION
**Pull request by anttileppa**
Resolves #65

### CODE REVIEW

File: edelphi/src/main/resources/fi/metatavu/edelphi/liquibase/query-template-settings-enc.sql [hunk 1]
```diff
@@ -0,0 +1,7 @@
+UPDATE LocalizedValue SET text = 'Ryhmä%201&Ryhmä%202' WHERE entry_id = (SELECT value_id FROM QueryPageTemplateSetting ts, QueryPageTemplateLocalizedSetting tls WHERE ts.key_id = (SELECT id FROM QueryPageSettingKey WHERE name = 'grouping.groups') and ts.id = tls.id) AND locale = 'fi';
+UPDATE LocalizedValue SET text = '-- Lisää otsikko --' WHERE entry_id = (SELECT value_id FROM QueryPageTemplateSetting ts, QueryPageTemplateLocalizedSetting tls WHERE ts.key_id = (SELECT id FROM QueryPageSettingKey WHERE name = 'time_serie.xAxisTitle') and ts.id = tls.id) AND locale = 'fi';
```
Comment (sonarq) [inline edelphi/src/main/resources/fi/metatavu/edelphi/liquibase/query-template-settings-enc.sql:2]: MINOR Define a constant instead of duplicating this literal '-- Lisää otsikko --' 4 times. [rule](https://sonarqube.com/coding_rules#rule_key=plsql%3AS1192)

**Comment by sonarq** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'
